### ISSUE TITLE
Allow versions of Laravel 8

### ISSUE THREAD

**Issue by lephuhai** [laravel-unleash/laravel-unleash#27]
Follow by installation guidelines and then getting an error. Please update to support Laravel 8. Thank you so much. <3

![image](https://user-images.githubusercontent.com/7351351/108616639-c2831980-7441-11eb-87d2-a787f06fed2b.png)

**Comment by mikefrancis** [comment]
Hi @lephuhai,

I'm pretty busy at the moment so feel free to submit a pull request if this is blocking you!

Thanks

**Comment by mikefrancis** [comment]
@lephuhai Just tested with a fresh install of Laravel 8 and installed the package with no issue.

You must have a dependency which is already tied to a very specific version of Guzzle.
