### ISSUE TITLE
Feature flags during test execution

### ISSUE THREAD

**Issue by thannaske** [laravel-unleash/laravel-unleash#31]
Is there any way to override all feature flags to be enabled during (offline) test execution? Currently, when laravel-unleash is set to disabled, everything acts like all flags are disabled which leads to failing tests.

**Comment by mikefrancis** [comment]
Hi @thannaske,

Not that I can think of. 

The reasoning behind this behaviour is it is more expected and safer; if you have sensitive data behind a feature toggle if is best to fail in favour of not showing something, rather than showing everything. Does that make sense?

I would say maybe change your implementation to suit the way the package works, or of course feel free to submit a PR for this.

**Comment by thannaske** [comment]
Thanks for getting back to me so quickly.

My practical issue is the following: I have implemented a payment functionality into a free web application for some additional features. I'm heavily test-driven and wrote feature tests to a) test that all the payment stuff works and b) that the user experience for non-paying users is still great. Both test suites depend on a different feature toggle state.

I'm using GitLab's built-in Unleash and there I need to provide the environment the toggle is valid for. Now I have a local development environment and a live production environment. Either the toggle is for both, then I would need to disable and enable the toggle for all users depending on my current testing activity which is obviously not an option. Or I build one toggle for the local env and one toggle for the production environment. But then I can only test locally, because before pushing to my master branch I would need to replace the name of local feature toggle with the name of the production feature toggle.

I want to work on that issue if you are open for contributions in that direction and I figured out two possible ways to resolve my issues. I'm eager to hear your opinion on them:

We could either add a section in the `config/unleash.php` file where we define default states for specific feature toggles that are varying from the default disabled-state. It could look like this:

```
[...]
// Globally control whether Unleash is enabled or disabled.
// If not enabled, no API requests will be made and all "enabled" checks will return `false` and
// "disabled" checks will return `true`.
'isEnabled' => env('UNLEASH_ENABLED', true),

// If Unleash is disabled and you want some specific feature toggles to be considered enabled instead of
// disabled you may specify their names below. All "enabled" checks for feature toggles listed below will then
// return `true` instead of `false`. This option does only apply when Unleash is disabled.
'disabledOverrides' => [
    'publicRegistration', 'paymentGateway-PayPal', 'paymentGateway-Stripe',
],
[...]
```

The other possibility is to just add testing helpers, like they are common in the Laravel universe:

```
/** @test */
public function the_registration_page_is_rendered()
{
    // In testing UNLEASH_ENABLED is set to false, so all feature-enabled checks will return false. 
    // This would cause this test to fail because the FeatureEnabled middleware would return a HTTP 404.
    // But with the new test helper we could things like this:
    Unleash::fake();
    Unleash::setEnabled('publicRegistration');
    $this->get('/register')->assertOk();

    Unleash::setDisabled('publicRegistration');
    $this->get('/register')->assertNotFound();
}
```

Personally I like the second alternative most, because it doesn't interfere that much with the current implementation. What do you think?

**Comment by mikefrancis** [comment]
Ah I see, yes then the second option is a great idea - I think the facade we expose is `Feature` so it would be `Feature::fake()` etc.
