### ISSUE TITLE
Cannot find JsonException (laravel 7)

### ISSUE THREAD

**Issue by iammikek** [laravel-unleash/laravel-unleash#35]
I've freshly installed Unleash on Laravel 7 and looking to use gitlab's featureFlagging.

Following https://github.com/mikefrancis/laravel-unleash

With the following implementation:

```
<?php

namespace App\Http\Controllers;

use MikeFrancis\LaravelUnleash\Facades\Unleash;

class FeatureFlagController extends Controller
{
    /**
     * @return mixed
     */
    public function __invoke()
    {
        return ['features' => Unleash::getFeatures()];
    }
}
```

I get the following error:
> Class 'Symfony\\Component\\HttpFoundation\\Exception\\JsonException' not found at /var/www/my-site/vendor/mikefrancis/laravel-unleash/src/Unleash.php:135)

if I edit `src/Unleash.php` and replace with:

> use JsonException;

I no longer get the error but dont see any features either.

I've found the the following issue: https://gitlab.com/gitlab-org/gitlab/-/issues/260612 which mentions about passing in app_name but can't see how to do this within laravel implementation.

Any pointers would be appreciated.

**Comment by mikefrancis** [comment]
@iammikek I think you need this part:

https://github.com/mikefrancis/laravel-unleash/blob/master/config/unleash.php#L14

**Comment by iammikek** [comment]
@mikefrancis I've uncommented the following:

```
  // Other default settings for requests to your Unleash server.
  'otherRequestDefaults' => [
    // Any other defaults for the request can be added here.
    // e.g. your Unleash server may require headers like these.
    //
     'headers' => [
       'UNLEASH-APPNAME' => env('UNLEASH_APPNAME', env('APP_ENV')),
       'UNLEASH-INSTANCEID' => env('UNLEASH_INSTANCEID'),
     ],
  ],
```
this should use my `APP_ENV` if I dont have `UNLEASH_APPNAME` defined.

Changing this doesn't have any effect though. 

locally my enviroment is running on docker and our gitlab is self hosted.

**Comment by mikefrancis** [comment]
@iammikek I believe you need a value for `UNLEASH_APPNAME` in order for this to work with GitLab.

You may be better asking on StackOverflow as I'm personally not in a position to support with this as its not an issue with the package.

I get a lot of people using this feature from GitLab (but it's not required or something I use myself) so if someone wanted to write up some instructions on how to use this I'd gladly accept a PR.

**Comment by iammikek** [comment]
@mikefrancis sure. I'll take my question over there.
