### ISSUE TITLE
Incompatible with Pest pestphp/pest (v1.20) 

### ISSUE THREAD

**Issue by bennyvdhoogen** [laravel-unleash/laravel-unleash#36]
Having this package installed seems to throw the following exception for us when we run our test suite via `./vendor/bin.pest`: 

`In TestSuite.php line 196:                                                                    
  Object of class Illuminate\Foundation\Application could not be converted to string`

PHP 8.0.11
laravel/framwork v.8.65.0
pestphp/pest v1.20

**Comment by mikefrancis** [comment]
@bennyvdhoogen Are you running these tests from within PHPStorm by any chance?

**Comment by bennyvdhoogen** [comment]
@mikefrancis just through the integrated VSCode terminal. Coworker using PHPStorm reported the same result though.

**Comment by mikefrancis** [comment]
@bennyvdhoogen Ah ok, just got a search result of someone having a similar issue and it sounded linked to PHPStorm/Docker but sounds like it's not.

I'm not a Pest PHP user so I think you may need to help out with debugging this, or possibly debug yourself, if you want to avoid this exception.

Are you able to provide some code examples?

**Comment by bennyvdhoogen** [comment]
@mikefrancis alright, if I can find some time I'll try to look into it myself and submit a PR. Our local development setup is Dockerized, so that could perhaps be related. I can't really provide any code samples as the error occurs in running the default 'run test suite' command. Running individual tests by specifying a folder works fine, so my hunch is that there must be some conflict between the way Pest indexes tests in folders and some proces that this package runs.

**Comment by mikefrancis** [comment]
@bennyvdhoogen These might help:

* https://github.com/Roboroads/laravel-tinker/issues/14
* https://stackoverflow.com/questions/29764368/fatal-error-class-illuminate-foundation-application-not-found
