### ISSUE TITLE
Set instanceId an Appname

### ISSUE THREAD

**Issue by RamonSmit** [laravel-unleash/laravel-unleash#9]
Hi there, 

Thanks for the Unleash package! I'm just scrolling trough the code and I'm wondering how I can set the instance id and app name via this package. 

Could you help me out with this? 

Thanks in advance,
Ramon

https://github.com/Unleash/unleash/blob/master/docs/api/client/feature-toggles-api.md#fetching-feature-toggles

**Comment by mikefrancis** [comment]
Hi!

This isn't possible with the current version of the package, however if you can submit a PR for it I'd gladly take a look.

I image we could use the [config](https://github.com/mikefrancis/laravel-unleash/blob/master/config/unleash.php#L7) to set these headers then pass them into to the [Guzzle client](https://github.com/mikefrancis/laravel-unleash/blob/master/src/Client.php#L15).

If you need to do this urgently, then you can always use [Laravel's service container](https://laravel.com/docs/6.x/container#binding) binding to override the client in this package with your own client that contains the headers:

```php
use MikeFrancis\LaravelUnleash\Client as UnleashGuzzleClient;

$this->app->singleton(UnleashGuzzleClient::class, function ($app) {
  return new UnleashGuzzleClient([
    'base_uri' => config('unleash.url'),
    'headers' => [
      'UNLEASH-APPNAME' => 'appName',
      'UNLEASH-INSTANCEID' => 'instanceId',
    ],
  ]);
});
```

I haven't tested that code but it should give you an idea!

**Comment by RamonSmit** [comment]
Thanks for your response! 

Well, it works! :-). Think i'm going to fork anytime soon and just submit a PR for this. 
It looks great to me. 

Thanks!
